"""update_flashcard_schema

Revision ID: 4f2f4c00f038
Revises: ee6c8479521c
Create Date: 2026-03-01 13:56:20.573776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2f4c00f038'
down_revision = 'ee6c8479521c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_flashcards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=False))
        batch_op.alter_column('difficulty',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_flashcards', schema=None) as batch_op:
        batch_op.alter_column('difficulty',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('order')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
